export {default as App} from './App'
export {default as Activities} from './Activities'
export {default as Login} from './Login'
export {default as MyRoutines} from './MyRoutines'
export {default as NavBar} from './NavBar'
export {default as Register} from './Register'
export {default as Routines} from './Routines'
export {default as Users} from './Users'